// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/v1/external.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RivalryServiceClient is the client API for RivalryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RivalryServiceClient interface {
	// route into matchmaking
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (RivalryService_MatchClient, error)
}

type rivalryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRivalryServiceClient(cc grpc.ClientConnInterface) RivalryServiceClient {
	return &rivalryServiceClient{cc}
}

func (c *rivalryServiceClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (RivalryService_MatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &RivalryService_ServiceDesc.Streams[0], "/api.v1.RivalryService/Match", opts...)
	if err != nil {
		return nil, err
	}
	x := &rivalryServiceMatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RivalryService_MatchClient interface {
	Recv() (*MatchResponse, error)
	grpc.ClientStream
}

type rivalryServiceMatchClient struct {
	grpc.ClientStream
}

func (x *rivalryServiceMatchClient) Recv() (*MatchResponse, error) {
	m := new(MatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RivalryServiceServer is the server API for RivalryService service.
// All implementations should embed UnimplementedRivalryServiceServer
// for forward compatibility
type RivalryServiceServer interface {
	// route into matchmaking
	Match(*MatchRequest, RivalryService_MatchServer) error
}

// UnimplementedRivalryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedRivalryServiceServer struct {
}

func (UnimplementedRivalryServiceServer) Match(*MatchRequest, RivalryService_MatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Match not implemented")
}

// UnsafeRivalryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RivalryServiceServer will
// result in compilation errors.
type UnsafeRivalryServiceServer interface {
	mustEmbedUnimplementedRivalryServiceServer()
}

func RegisterRivalryServiceServer(s grpc.ServiceRegistrar, srv RivalryServiceServer) {
	s.RegisterService(&RivalryService_ServiceDesc, srv)
}

func _RivalryService_Match_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RivalryServiceServer).Match(m, &rivalryServiceMatchServer{stream})
}

type RivalryService_MatchServer interface {
	Send(*MatchResponse) error
	grpc.ServerStream
}

type rivalryServiceMatchServer struct {
	grpc.ServerStream
}

func (x *rivalryServiceMatchServer) Send(m *MatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

// RivalryService_ServiceDesc is the grpc.ServiceDesc for RivalryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RivalryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.RivalryService",
	HandlerType: (*RivalryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Match",
			Handler:       _RivalryService_Match_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/external.proto",
}
