// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: api/v1/match_logic.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeMatchesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Submissions []*Submission `protobuf:"bytes,1,rep,name=submissions,proto3" json:"submissions,omitempty"`
}

func (x *MakeMatchesRequest) Reset() {
	*x = MakeMatchesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_match_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMatchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMatchesRequest) ProtoMessage() {}

func (x *MakeMatchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_match_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMatchesRequest.ProtoReflect.Descriptor instead.
func (*MakeMatchesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_match_logic_proto_rawDescGZIP(), []int{0}
}

func (x *MakeMatchesRequest) GetSubmissions() []*Submission {
	if x != nil {
		return x.Submissions
	}
	return nil
}

type Submission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// a UUID generated by the client
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// list of player ids linked to this request
	Members []string `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	// matchmaking data specific to this player / group
	MatchRequestData *MatchRequestData `protobuf:"bytes,3,opt,name=match_request_data,json=matchRequestData,proto3" json:"match_request_data,omitempty"`
	// A queue is a collection of tickets to be matched together, it controls how tickets are matched
	MatchmakingQueue string `protobuf:"bytes,4,opt,name=matchmaking_queue,json=matchmakingQueue,proto3" json:"matchmaking_queue,omitempty"`
	// A list of latency data for game server instances
	Rtts []*RTT `protobuf:"bytes,5,rep,name=rtts,proto3" json:"rtts,omitempty"`
	// record the time the ticket was created in the db
	CreateTime int64 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *Submission) Reset() {
	*x = Submission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_match_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_match_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_api_v1_match_logic_proto_rawDescGZIP(), []int{1}
}

func (x *Submission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Submission) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *Submission) GetMatchRequestData() *MatchRequestData {
	if x != nil {
		return x.MatchRequestData
	}
	return nil
}

func (x *Submission) GetMatchmakingQueue() string {
	if x != nil {
		return x.MatchmakingQueue
	}
	return ""
}

func (x *Submission) GetRtts() []*RTT {
	if x != nil {
		return x.Rtts
	}
	return nil
}

func (x *Submission) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type MakeMatchesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Match *Match `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
}

func (x *MakeMatchesResponse) Reset() {
	*x = MakeMatchesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_match_logic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeMatchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMatchesResponse) ProtoMessage() {}

func (x *MakeMatchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_match_logic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMatchesResponse.ProtoReflect.Descriptor instead.
func (*MakeMatchesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_match_logic_proto_rawDescGZIP(), []int{2}
}

func (x *MakeMatchesResponse) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A UUID that should be passed through the stack for tracing.
	MatchId string `protobuf:"bytes,1,opt,name=match_id,proto3" json:"match_id,omitempty"`
	// Name of the matchmaking queue this match was created on.
	MatchmakingQueue string `protobuf:"bytes,2,opt,name=matchmaking_queue,proto3" json:"matchmaking_queue,omitempty"`
	// Match Request IDs that belong to this match.
	MatchRequestIds []string `protobuf:"bytes,3,rep,name=match_request_ids,proto3" json:"match_request_ids,omitempty"`
	// list of player ids linked to this request
	PlayerIds []string `protobuf:"bytes,4,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	// A list of average latency data for game server instances
	Rtts []*RTT `protobuf:"bytes,5,rep,name=rtts,proto3" json:"rtts,omitempty"`
}

func (x *Match) Reset() {
	*x = Match{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_match_logic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_match_logic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_api_v1_match_logic_proto_rawDescGZIP(), []int{3}
}

func (x *Match) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Match) GetMatchmakingQueue() string {
	if x != nil {
		return x.MatchmakingQueue
	}
	return ""
}

func (x *Match) GetMatchRequestIds() []string {
	if x != nil {
		return x.MatchRequestIds
	}
	return nil
}

func (x *Match) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *Match) GetRtts() []*RTT {
	if x != nil {
		return x.Rtts
	}
	return nil
}

type MakeAssignmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Match *Match `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
}

func (x *MakeAssignmentRequest) Reset() {
	*x = MakeAssignmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_match_logic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAssignmentRequest) ProtoMessage() {}

func (x *MakeAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_match_logic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAssignmentRequest.ProtoReflect.Descriptor instead.
func (*MakeAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_match_logic_proto_rawDescGZIP(), []int{4}
}

func (x *MakeAssignmentRequest) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

type MakeAssignmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServer *GameServer `protobuf:"bytes,1,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
}

func (x *MakeAssignmentResponse) Reset() {
	*x = MakeAssignmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_match_logic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeAssignmentResponse) ProtoMessage() {}

func (x *MakeAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_match_logic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeAssignmentResponse.ProtoReflect.Descriptor instead.
func (*MakeAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_match_logic_proto_rawDescGZIP(), []int{5}
}

func (x *MakeAssignmentResponse) GetGameServer() *GameServer {
	if x != nil {
		return x.GameServer
	}
	return nil
}

var File_api_v1_match_logic_proto protoreflect.FileDescriptor

var file_api_v1_match_logic_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x1a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x12, 0x4d, 0x61, 0x6b,
	0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x34, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xed, 0x01, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x46,
	0x0a, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x10, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d,
	0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x74, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x54, 0x54, 0x52, 0x04,
	0x72, 0x74, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x13, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x22, 0xbf, 0x01, 0x0a, 0x05, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x11, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x74, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x54, 0x54, 0x52, 0x04, 0x72,
	0x74, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x15, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x05,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x22, 0x4d, 0x0a, 0x16, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x32, 0x5f, 0x0a, 0x11, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61,
	0x6b, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x32, 0x66, 0x0a, 0x11, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x72, 0x79, 0x2d,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x72, 0x69, 0x76, 0x61, 0x6c,
	0x72, 0x79, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_match_logic_proto_rawDescOnce sync.Once
	file_api_v1_match_logic_proto_rawDescData = file_api_v1_match_logic_proto_rawDesc
)

func file_api_v1_match_logic_proto_rawDescGZIP() []byte {
	file_api_v1_match_logic_proto_rawDescOnce.Do(func() {
		file_api_v1_match_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_match_logic_proto_rawDescData)
	})
	return file_api_v1_match_logic_proto_rawDescData
}

var file_api_v1_match_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_v1_match_logic_proto_goTypes = []interface{}{
	(*MakeMatchesRequest)(nil),     // 0: api.v1.MakeMatchesRequest
	(*Submission)(nil),             // 1: api.v1.Submission
	(*MakeMatchesResponse)(nil),    // 2: api.v1.MakeMatchesResponse
	(*Match)(nil),                  // 3: api.v1.Match
	(*MakeAssignmentRequest)(nil),  // 4: api.v1.MakeAssignmentRequest
	(*MakeAssignmentResponse)(nil), // 5: api.v1.MakeAssignmentResponse
	(*MatchRequestData)(nil),       // 6: api.v1.MatchRequestData
	(*RTT)(nil),                    // 7: api.v1.RTT
	(*GameServer)(nil),             // 8: api.v1.GameServer
}
var file_api_v1_match_logic_proto_depIdxs = []int32{
	1, // 0: api.v1.MakeMatchesRequest.submissions:type_name -> api.v1.Submission
	6, // 1: api.v1.Submission.match_request_data:type_name -> api.v1.MatchRequestData
	7, // 2: api.v1.Submission.rtts:type_name -> api.v1.RTT
	3, // 3: api.v1.MakeMatchesResponse.match:type_name -> api.v1.Match
	7, // 4: api.v1.Match.rtts:type_name -> api.v1.RTT
	3, // 5: api.v1.MakeAssignmentRequest.match:type_name -> api.v1.Match
	8, // 6: api.v1.MakeAssignmentResponse.game_server:type_name -> api.v1.GameServer
	0, // 7: api.v1.MatchMakerService.MakeMatches:input_type -> api.v1.MakeMatchesRequest
	4, // 8: api.v1.AssignmentService.MakeAssignment:input_type -> api.v1.MakeAssignmentRequest
	2, // 9: api.v1.MatchMakerService.MakeMatches:output_type -> api.v1.MakeMatchesResponse
	5, // 10: api.v1.AssignmentService.MakeAssignment:output_type -> api.v1.MakeAssignmentResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1_match_logic_proto_init() }
func file_api_v1_match_logic_proto_init() {
	if File_api_v1_match_logic_proto != nil {
		return
	}
	file_api_v1_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_match_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeMatchesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_match_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Submission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_match_logic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeMatchesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_match_logic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Match); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_match_logic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeAssignmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_match_logic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeAssignmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_match_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_v1_match_logic_proto_goTypes,
		DependencyIndexes: file_api_v1_match_logic_proto_depIdxs,
		MessageInfos:      file_api_v1_match_logic_proto_msgTypes,
	}.Build()
	File_api_v1_match_logic_proto = out.File
	file_api_v1_match_logic_proto_rawDesc = nil
	file_api_v1_match_logic_proto_goTypes = nil
	file_api_v1_match_logic_proto_depIdxs = nil
}
