apiVersion: rivalry.rivalry/v1alpha1
kind: Profile
metadata:
  name: profile-example
spec:
  nats_address: nats://nats.default.svc.cluster.local:4222
  redis_address: redis-master.default.svc.cluster.local:6379
  frontend_service:
    image: 192.168.64.136:5000/rivalry-frontend:latest
  accumulator_service:
    image: 192.168.64.136:5000/rivalry-accumulator:latest
  matcher_service:
    image: 192.168.64.136:5000/rivalry-matcher:latest
  dispenser_service:
    image: 192.168.64.136:5000/rivalry-dispenser:latest
    assignment_target: assignment.default.svc.cluster.local:50051
  matchmaking_queues:
  - name: default
    matchmaker_target: matchmaker.default.svc.cluster.local:50051
    max_tickets: 2
  - name: 2v2
    matchmaker_target: matchmaker.default.svc.cluster.local:50051
    max_tickets: 4
