// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rivalry-matchmaker/rivalry/pkg/pb/api/v1 (interfaces: MatchMakerServiceClient,MatchMakerService_MakeMatchesClient,MatchMakerServiceServer,UnsafeMatchMakerServiceServer,MatchMakerService_MakeMatchesServer,AssignmentServiceClient,AssignmentServiceServer,UnsafeAssignmentServiceServer)

// Package mock_pb is a generated GoMock package.
package mock_pb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/rivalry-matchmaker/rivalry/pkg/pb/api/v1"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockMatchMakerServiceClient is a mock of MatchMakerServiceClient interface.
type MockMatchMakerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMatchMakerServiceClientMockRecorder
}

// MockMatchMakerServiceClientMockRecorder is the mock recorder for MockMatchMakerServiceClient.
type MockMatchMakerServiceClientMockRecorder struct {
	mock *MockMatchMakerServiceClient
}

// NewMockMatchMakerServiceClient creates a new mock instance.
func NewMockMatchMakerServiceClient(ctrl *gomock.Controller) *MockMatchMakerServiceClient {
	mock := &MockMatchMakerServiceClient{ctrl: ctrl}
	mock.recorder = &MockMatchMakerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchMakerServiceClient) EXPECT() *MockMatchMakerServiceClientMockRecorder {
	return m.recorder
}

// MakeMatches mocks base method.
func (m *MockMatchMakerServiceClient) MakeMatches(arg0 context.Context, arg1 *v1.MakeMatchesRequest, arg2 ...grpc.CallOption) (v1.MatchMakerService_MakeMatchesClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeMatches", varargs...)
	ret0, _ := ret[0].(v1.MatchMakerService_MakeMatchesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeMatches indicates an expected call of MakeMatches.
func (mr *MockMatchMakerServiceClientMockRecorder) MakeMatches(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeMatches", reflect.TypeOf((*MockMatchMakerServiceClient)(nil).MakeMatches), varargs...)
}

// MockMatchMakerService_MakeMatchesClient is a mock of MatchMakerService_MakeMatchesClient interface.
type MockMatchMakerService_MakeMatchesClient struct {
	ctrl     *gomock.Controller
	recorder *MockMatchMakerService_MakeMatchesClientMockRecorder
}

// MockMatchMakerService_MakeMatchesClientMockRecorder is the mock recorder for MockMatchMakerService_MakeMatchesClient.
type MockMatchMakerService_MakeMatchesClientMockRecorder struct {
	mock *MockMatchMakerService_MakeMatchesClient
}

// NewMockMatchMakerService_MakeMatchesClient creates a new mock instance.
func NewMockMatchMakerService_MakeMatchesClient(ctrl *gomock.Controller) *MockMatchMakerService_MakeMatchesClient {
	mock := &MockMatchMakerService_MakeMatchesClient{ctrl: ctrl}
	mock.recorder = &MockMatchMakerService_MakeMatchesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchMakerService_MakeMatchesClient) EXPECT() *MockMatchMakerService_MakeMatchesClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).Context))
}

// Header mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) Recv() (*v1.MakeMatchesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.MakeMatchesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockMatchMakerService_MakeMatchesClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockMatchMakerService_MakeMatchesClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockMatchMakerService_MakeMatchesClient)(nil).Trailer))
}

// MockMatchMakerServiceServer is a mock of MatchMakerServiceServer interface.
type MockMatchMakerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockMatchMakerServiceServerMockRecorder
}

// MockMatchMakerServiceServerMockRecorder is the mock recorder for MockMatchMakerServiceServer.
type MockMatchMakerServiceServerMockRecorder struct {
	mock *MockMatchMakerServiceServer
}

// NewMockMatchMakerServiceServer creates a new mock instance.
func NewMockMatchMakerServiceServer(ctrl *gomock.Controller) *MockMatchMakerServiceServer {
	mock := &MockMatchMakerServiceServer{ctrl: ctrl}
	mock.recorder = &MockMatchMakerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchMakerServiceServer) EXPECT() *MockMatchMakerServiceServerMockRecorder {
	return m.recorder
}

// MakeMatches mocks base method.
func (m *MockMatchMakerServiceServer) MakeMatches(arg0 *v1.MakeMatchesRequest, arg1 v1.MatchMakerService_MakeMatchesServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeMatches", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MakeMatches indicates an expected call of MakeMatches.
func (mr *MockMatchMakerServiceServerMockRecorder) MakeMatches(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeMatches", reflect.TypeOf((*MockMatchMakerServiceServer)(nil).MakeMatches), arg0, arg1)
}

// MockUnsafeMatchMakerServiceServer is a mock of UnsafeMatchMakerServiceServer interface.
type MockUnsafeMatchMakerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeMatchMakerServiceServerMockRecorder
}

// MockUnsafeMatchMakerServiceServerMockRecorder is the mock recorder for MockUnsafeMatchMakerServiceServer.
type MockUnsafeMatchMakerServiceServerMockRecorder struct {
	mock *MockUnsafeMatchMakerServiceServer
}

// NewMockUnsafeMatchMakerServiceServer creates a new mock instance.
func NewMockUnsafeMatchMakerServiceServer(ctrl *gomock.Controller) *MockUnsafeMatchMakerServiceServer {
	mock := &MockUnsafeMatchMakerServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeMatchMakerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeMatchMakerServiceServer) EXPECT() *MockUnsafeMatchMakerServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedMatchMakerServiceServer mocks base method.
func (m *MockUnsafeMatchMakerServiceServer) mustEmbedUnimplementedMatchMakerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedMatchMakerServiceServer")
}

// mustEmbedUnimplementedMatchMakerServiceServer indicates an expected call of mustEmbedUnimplementedMatchMakerServiceServer.
func (mr *MockUnsafeMatchMakerServiceServerMockRecorder) mustEmbedUnimplementedMatchMakerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedMatchMakerServiceServer", reflect.TypeOf((*MockUnsafeMatchMakerServiceServer)(nil).mustEmbedUnimplementedMatchMakerServiceServer))
}

// MockMatchMakerService_MakeMatchesServer is a mock of MatchMakerService_MakeMatchesServer interface.
type MockMatchMakerService_MakeMatchesServer struct {
	ctrl     *gomock.Controller
	recorder *MockMatchMakerService_MakeMatchesServerMockRecorder
}

// MockMatchMakerService_MakeMatchesServerMockRecorder is the mock recorder for MockMatchMakerService_MakeMatchesServer.
type MockMatchMakerService_MakeMatchesServerMockRecorder struct {
	mock *MockMatchMakerService_MakeMatchesServer
}

// NewMockMatchMakerService_MakeMatchesServer creates a new mock instance.
func NewMockMatchMakerService_MakeMatchesServer(ctrl *gomock.Controller) *MockMatchMakerService_MakeMatchesServer {
	mock := &MockMatchMakerService_MakeMatchesServer{ctrl: ctrl}
	mock.recorder = &MockMatchMakerService_MakeMatchesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchMakerService_MakeMatchesServer) EXPECT() *MockMatchMakerService_MakeMatchesServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).RecvMsg), arg0)
}

// Send mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) Send(arg0 *v1.MakeMatchesResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockMatchMakerService_MakeMatchesServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockMatchMakerService_MakeMatchesServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockMatchMakerService_MakeMatchesServer)(nil).SetTrailer), arg0)
}

// MockAssignmentServiceClient is a mock of AssignmentServiceClient interface.
type MockAssignmentServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAssignmentServiceClientMockRecorder
}

// MockAssignmentServiceClientMockRecorder is the mock recorder for MockAssignmentServiceClient.
type MockAssignmentServiceClientMockRecorder struct {
	mock *MockAssignmentServiceClient
}

// NewMockAssignmentServiceClient creates a new mock instance.
func NewMockAssignmentServiceClient(ctrl *gomock.Controller) *MockAssignmentServiceClient {
	mock := &MockAssignmentServiceClient{ctrl: ctrl}
	mock.recorder = &MockAssignmentServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssignmentServiceClient) EXPECT() *MockAssignmentServiceClientMockRecorder {
	return m.recorder
}

// MakeAssignment mocks base method.
func (m *MockAssignmentServiceClient) MakeAssignment(arg0 context.Context, arg1 *v1.MakeAssignmentRequest, arg2 ...grpc.CallOption) (*v1.MakeAssignmentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeAssignment", varargs...)
	ret0, _ := ret[0].(*v1.MakeAssignmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeAssignment indicates an expected call of MakeAssignment.
func (mr *MockAssignmentServiceClientMockRecorder) MakeAssignment(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeAssignment", reflect.TypeOf((*MockAssignmentServiceClient)(nil).MakeAssignment), varargs...)
}

// MockAssignmentServiceServer is a mock of AssignmentServiceServer interface.
type MockAssignmentServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockAssignmentServiceServerMockRecorder
}

// MockAssignmentServiceServerMockRecorder is the mock recorder for MockAssignmentServiceServer.
type MockAssignmentServiceServerMockRecorder struct {
	mock *MockAssignmentServiceServer
}

// NewMockAssignmentServiceServer creates a new mock instance.
func NewMockAssignmentServiceServer(ctrl *gomock.Controller) *MockAssignmentServiceServer {
	mock := &MockAssignmentServiceServer{ctrl: ctrl}
	mock.recorder = &MockAssignmentServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssignmentServiceServer) EXPECT() *MockAssignmentServiceServerMockRecorder {
	return m.recorder
}

// MakeAssignment mocks base method.
func (m *MockAssignmentServiceServer) MakeAssignment(arg0 context.Context, arg1 *v1.MakeAssignmentRequest) (*v1.MakeAssignmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeAssignment", arg0, arg1)
	ret0, _ := ret[0].(*v1.MakeAssignmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeAssignment indicates an expected call of MakeAssignment.
func (mr *MockAssignmentServiceServerMockRecorder) MakeAssignment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeAssignment", reflect.TypeOf((*MockAssignmentServiceServer)(nil).MakeAssignment), arg0, arg1)
}

// MockUnsafeAssignmentServiceServer is a mock of UnsafeAssignmentServiceServer interface.
type MockUnsafeAssignmentServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeAssignmentServiceServerMockRecorder
}

// MockUnsafeAssignmentServiceServerMockRecorder is the mock recorder for MockUnsafeAssignmentServiceServer.
type MockUnsafeAssignmentServiceServerMockRecorder struct {
	mock *MockUnsafeAssignmentServiceServer
}

// NewMockUnsafeAssignmentServiceServer creates a new mock instance.
func NewMockUnsafeAssignmentServiceServer(ctrl *gomock.Controller) *MockUnsafeAssignmentServiceServer {
	mock := &MockUnsafeAssignmentServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeAssignmentServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeAssignmentServiceServer) EXPECT() *MockUnsafeAssignmentServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedAssignmentServiceServer mocks base method.
func (m *MockUnsafeAssignmentServiceServer) mustEmbedUnimplementedAssignmentServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAssignmentServiceServer")
}

// mustEmbedUnimplementedAssignmentServiceServer indicates an expected call of mustEmbedUnimplementedAssignmentServiceServer.
func (mr *MockUnsafeAssignmentServiceServerMockRecorder) mustEmbedUnimplementedAssignmentServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAssignmentServiceServer", reflect.TypeOf((*MockUnsafeAssignmentServiceServer)(nil).mustEmbedUnimplementedAssignmentServiceServer))
}
